# include:
#   - ./img/docker-compose.yml

services:
  traefik:
    image: traefik:v2.4
    command:
      - --api.insecure=true
      - --providers.docker
      - --entrypoints.gateway.address=:727
    ports:
      - "727:727"
      - "7878:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  web:
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.web.rule=Host("thiccmc.com", "localhost") && PathPrefix(`/`)'
      - "traefik.http.routers.web.entrypoints=gateway"
    build: web
    env_file:
      - ./.env.production
    expose:
      - 3000
  api:
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.auth.rule=Host("thiccmc.com", "api.localhost") && PathPrefix(`/`)'
      - "traefik.http.routers.auth.entrypoints=gateway"
    build: nut
    env_file:
      - ./.env.production
    expose:
      - 8080
